language: node_js
addons:
  apt:
    update: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- -version 1.16.0
  - export PATH=$HOME/.yarn/bin:$PATH

node_js:
  - 'lts/*'

cache:
  directories:
    - node_modules
    - ~/.yarn

deploy:
  provider: script
  script:
    - git config --global user.name "${GH_NAME}"
    - git config --global user.email "${GH_EMAIL}"
    - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
    - cd website && yarn install && GIT_USER="${GH_NAME}" yarn run
      publish-gh-pages
  on: 
    branch: master
